server:
  port: 8000
  tomcat:
    uri-encoding: utf-8

spring:
  mvc:
    pathmatch:
      #swagger null point 'documentationPluginsBootstrapper' 에러 해결
      matching-strategy: ant_path_matcher
  datasource:
    # 데이버 베이스 driver 이름
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 데이터베이스 로그인 아이디
    username: lossleaderback
    # 데이터베이스 로그인 비밀번호
    password: lossleaderBack12!
    # 데이터베이스 url
    url: jdbc:mysql://218.55.129.211:3306/lossleader
  jpa:
    hibernate:
      # create-drop : 서버 실행할때 drop 및 생성을 실행하고 서버 종료시 drop 실행
      # update : 변경될 스키마 적용
      # create : 서버 실행 할때마다 생성된 데이터베이스를 다 삭제하고 새로 create
      ddl-auto: none
    generate-ddl: true
    show-sql: true
  mail:
    port: 587
    host: smtp.gmail.com
    username: cousim55@gmail.com
    password: yfktjvsgtnfqjglx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: MrLhZGLeBYRF_Uy9YwY3
            client-secret: UHa2lICTGf
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/login
          kakao:
            client-id: 066cdaa50bdaebd7e266d0ca6d6c4b2c
            client-secret: RMKwFgHIgi7sYJG6Jbu5uKB8jZTXVN8B
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/login
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

minio:
  end_point: http://localhost:9000
  access_key: lossleader
  secret_key: lossleader123